### PR TITLE
Tune down logging when registering tracing, now at FINE level

### PR DESCRIPTION
**Pull request by mpetazzoni**
Those log messages are really intrusive on large web applications with many resources.

### CODE REVIEW

**Comment by jpkrohling** [comment]
This is shown once per JAX-RS resource, right? Could you confirm whether we have a similar log entry at `INFO` level for the deployment? We'd need *one* log entry to positively confirm the integration is active.

**Comment by mpetazzoni** [comment]
Yes, this log message happens once per discovered resource. Ideally I would want to see something like this (with log levels):

```
DEBUG: ServerTracingDynamicFeature registered tracing: MyResource#myFirstEndpoint
DEBUG: ServerTracingDynamicFeature registered tracing: MyResource#mySecondEndpoint
DEBUG: ServerTracingDynamicFeature registered tracing: MyOtherResource#myOtherEndpoint
INFO: ServerTracingDynamicFeature registered tracing for 3 methods across 2 resources
```

Unfortunately there doesn't seem to be any other hooks during which to display a more succinct, summary log message like above.

Also of note, in my setup, WADL's OptionsMethodProcessor is being shown for every resource method:

```
Aug 05, 2017 12:04:57 AM io.opentracing.contrib.jaxrs2.server.ServerTracingDynamicFeature configure
INFO: io.opentracing.contrib.jaxrs2.server.ServerTracingDynamicFeature@469d418e registering tracing: org.glassfish.jersey.server.wadl.processor.OptionsMethodProcessor.PlainTextOptionsInflector#apply
Aug 05, 2017 12:04:57 AM io.opentracing.contrib.jaxrs2.server.ServerTracingDynamicFeature configure
INFO: io.opentracing.contrib.jaxrs2.server.ServerTracingDynamicFeature@469d418e registering tracing: org.glassfish.jersey.server.wadl.processor.OptionsMethodProcessor.GenericOptionsInflector#apply
Aug 05, 2017 12:04:57 AM io.opentracing.contrib.jaxrs2.server.ServerTracingDynamicFeature configure
INFO: io.opentracing.contrib.jaxrs2.server.ServerTracingDynamicFeature@469d418e registering tracing: sf.rest.v2.resource.DetectorResource#enable
```

So as you might imagine, it adds up...

**Comment by jpkrohling** [comment]
But is there a way to get it logged only once per deployment? For instance, would it be possible to get access to the `servletContext` from within this routine? If so, a solution could be to add a flag to it as a property, indicating whether or not a notification has been put on the logs already. Or even a static `AtomicBoolean`?

**Comment by mpetazzoni** [comment]
This should be better

**Comment by pavolloffay** [comment]
LGTM, how the logs look now?

**Comment by mpetazzoni** [comment]
As expected; at FINE level, you see one log message per resource method being traced. At INFO level, you see only one message:

```
INFO: io.opentracing.contrib.jaxrs2.server.ServerTracingDynamicFeature@6913c1fb registering tracing on deployed resources
```

If this sounds fine to you, I think it's ready to merge. Would love a 0.0.9 release with this and #40, if you can!

**Comment by pavolloffay** [comment]
LGTM, thanks @mpetazzoni 

@jpkrohling is it fine?

**Comment by jpkrohling** [comment]
LGTM, although I'd say that the printing out the instance isn't that necessary :-) I have no problems in doing that in a follow up PR, if preferred.

```
io.opentracing.contrib.jaxrs2.server.ServerTracingDynamicFeature@6913c1fb
```

**Comment by mpetazzoni** [comment]
I thought so too but didn't want to change things too much at first. Done!

**Comment by pavolloffay** [comment]
I will cut a new release now

**Comment by pavolloffay** [comment]
@mpetazzoni thanks!

**Comment by mpetazzoni** [comment]
Awesome, thanks @pavolloffay and @jpkrohling

**Pull request merged**
