### PR TITLE
Use wildcard wildcard as a default operation name for server spans

### PR DESCRIPTION
**Pull request by pavolloffay**
Use wildcard path as a default operation name for server spans.

cc @bhs @yurishkuro

### CODE REVIEW

**Comment by yurishkuro** [comment]
How come no tests need to change?

**Comment by pavolloffay** [comment]
There already have been tests for both decorators. This PR just adds wildcard decorator to a default set of decorators. In test tracing feature is created with builder specifying a set of decorators.

**Comment by yurishkuro** [comment]
in my experience people prefer as little customization as possible, relying on the default behavior. So backwards compatibility of the default behavior is important to have its own tests.

**Comment by pavolloffay** [comment]
Agree, this is the main reason of this PR. I'm going to restructure tests in the next PR.

**Pull request merged**
